// Devises courantes pour nomades digitaux — liste volontairement curatée
// (pas les ~180 devises ISO) pour un <select> lisible.
export const CURRENCIES = [
  { code: 'EUR', name: 'Euro' },
  { code: 'USD', name: 'Dollar américain' },
  { code: 'GBP', name: 'Livre sterling' },
  { code: 'CHF', name: 'Franc suisse' },
  { code: 'THB', name: 'Baht thaïlandais' },
  { code: 'VND', name: 'Dong vietnamien' },
  { code: 'IDR', name: 'Roupie indonésienne' },
  { code: 'MYR', name: 'Ringgit malaisien' },
  { code: 'SGD', name: 'Dollar de Singapour' },
  { code: 'PHP', name: 'Peso philippin' },
  { code: 'KHR', name: 'Riel cambodgien' },
  { code: 'LAK', name: 'Kip laotien' },
  { code: 'MMK', name: 'Kyat birman' },
  { code: 'JPY', name: 'Yen japonais' },
  { code: 'KRW', name: 'Won sud-coréen' },
  { code: 'CNY', name: 'Yuan chinois' },
  { code: 'TWD', name: 'Dollar taïwanais' },
  { code: 'HKD', name: 'Dollar de Hong Kong' },
  { code: 'INR', name: 'Roupie indienne' },
  { code: 'NPR', name: 'Roupie népalaise' },
  { code: 'LKR', name: 'Roupie srilankaise' },
  { code: 'BDT', name: 'Taka bangladais' },
  { code: 'TRY', name: 'Livre turque' },
  { code: 'GEL', name: 'Lari géorgien' },
  { code: 'AMD', name: 'Dram arménien' },
  { code: 'AED', name: 'Dirham des Émirats' },
  { code: 'SAR', name: 'Riyal saoudien' },
  { code: 'QAR', name: 'Riyal qatari' },
  { code: 'ILS', name: 'Shekel israélien' },
  { code: 'JOD', name: 'Dinar jordanien' },
  { code: 'EGP', name: 'Livre égyptienne' },
  { code: 'MAD', name: 'Dirham marocain' },
  { code: 'TND', name: 'Dinar tunisien' },
  { code: 'ZAR', name: 'Rand sud-africain' },
  { code: 'KES', name: 'Shilling kényan' },
  { code: 'TZS', name: 'Shilling tanzanien' },
  { code: 'NGN', name: 'Naira nigérian' },
  { code: 'GHS', name: 'Cedi ghanéen' },
  { code: 'MXN', name: 'Peso mexicain' },
  { code: 'BRL', name: 'Real brésilien' },
  { code: 'ARS', name: 'Peso argentin' },
  { code: 'CLP', name: 'Peso chilien' },
  { code: 'COP', name: 'Peso colombien' },
  { code: 'PEN', name: 'Sol péruvien' },
  { code: 'BOB', name: 'Boliviano' },
  { code: 'UYU', name: 'Peso uruguayen' },
  { code: 'PYG', name: 'Guaraní paraguayen' },
  { code: 'CAD', name: 'Dollar canadien' },
  { code: 'AUD', name: 'Dollar australien' },
  { code: 'NZD', name: 'Dollar néo-zélandais' },
  { code: 'PLN', name: 'Zloty polonais' },
  { code: 'CZK', name: 'Couronne tchèque' },
  { code: 'HUF', name: 'Forint hongrois' },
  { code: 'RON', name: 'Leu roumain' },
  { code: 'BGN', name: 'Lev bulgare' },
  { code: 'RSD', name: 'Dinar serbe' },
  { code: 'ALL', name: 'Lek albanais' },
  { code: 'DKK', name: 'Couronne danoise' },
  { code: 'SEK', name: 'Couronne suédoise' },
  { code: 'NOK', name: 'Couronne norvégienne' },
  { code: 'ISK', name: 'Couronne islandaise' },
  { code: 'RUB', name: 'Rouble russe' },
  { code: 'KZT', name: 'Tenge kazakh' },
] as const

export type CurrencyCode = (typeof CURRENCIES)[number]['code']
